# Generated by Django 5.1.1 on 2024-10-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='payment_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ID платежа'),
        ),
    ]
