# Generated by Django 5.1.1 on 2024-09-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/learning', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/learning', verbose_name='Изображение'),
        ),
    ]
