# Generated by Django 5.1.1 on 2024-10-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость урока'),
        ),
    ]
